// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/services": {
    params: {};
  };
  "/dashboard/services/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/audit-logs": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/settings/email-templates": {
    params: {};
  };
  "/dashboard/settings/email-templates/:type": {
    params: {
      "type": string;
    };
  };
  "/dashboard/settings/branding": {
    params: {};
  };
  "/dashboard/settings/email": {
    params: {};
  };
  "/dashboard/tenants": {
    params: {};
  };
  "/dashboard/tenants/:tenantId/invitations": {
    params: {
      "tenantId": string;
    };
  };
  "/dashboard/roles": {
    params: {};
  };
  "/dashboard/users": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/dashboard/services" | "/dashboard/services/:id" | "/dashboard/audit-logs" | "/dashboard/settings" | "/dashboard/settings/email-templates" | "/dashboard/settings/email-templates/:type" | "/dashboard/settings/branding" | "/dashboard/settings/email" | "/dashboard/tenants" | "/dashboard/tenants/:tenantId/invitations" | "/dashboard/roles" | "/dashboard/users" | "/register" | "/login";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/services" | "/dashboard/services/:id" | "/dashboard/audit-logs" | "/dashboard/settings" | "/dashboard/settings/email-templates" | "/dashboard/settings/email-templates/:type" | "/dashboard/settings/branding" | "/dashboard/settings/email" | "/dashboard/tenants" | "/dashboard/tenants/:tenantId/invitations" | "/dashboard/roles" | "/dashboard/users";
  };
  "routes/dashboard.services._index.tsx": {
    id: "routes/dashboard.services._index";
    page: "/dashboard/services";
  };
  "routes/dashboard.services.$id.tsx": {
    id: "routes/dashboard.services.$id";
    page: "/dashboard/services/:id";
  };
  "routes/dashboard.audit-logs.tsx": {
    id: "routes/dashboard.audit-logs";
    page: "/dashboard/audit-logs";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings" | "/dashboard/settings/email-templates" | "/dashboard/settings/email-templates/:type" | "/dashboard/settings/branding" | "/dashboard/settings/email";
  };
  "routes/dashboard.settings.email-templates._index.tsx": {
    id: "routes/dashboard.settings.email-templates._index";
    page: "/dashboard/settings/email-templates";
  };
  "routes/dashboard.settings.email-templates.$type.tsx": {
    id: "routes/dashboard.settings.email-templates.$type";
    page: "/dashboard/settings/email-templates/:type";
  };
  "routes/dashboard.settings.branding.tsx": {
    id: "routes/dashboard.settings.branding";
    page: "/dashboard/settings/branding";
  };
  "routes/dashboard.settings._index.tsx": {
    id: "routes/dashboard.settings._index";
    page: "/dashboard/settings";
  };
  "routes/dashboard.settings.email.tsx": {
    id: "routes/dashboard.settings.email";
    page: "/dashboard/settings/email";
  };
  "routes/dashboard.tenants.tsx": {
    id: "routes/dashboard.tenants";
    page: "/dashboard/tenants" | "/dashboard/tenants/:tenantId/invitations";
  };
  "routes/dashboard.tenants.$tenantId.invitations.tsx": {
    id: "routes/dashboard.tenants.$tenantId.invitations";
    page: "/dashboard/tenants/:tenantId/invitations";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.roles.tsx": {
    id: "routes/dashboard.roles";
    page: "/dashboard/roles";
  };
  "routes/dashboard.users.tsx": {
    id: "routes/dashboard.users";
    page: "/dashboard/users";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard.services._index": typeof import("./app/routes/dashboard.services._index.tsx");
  "routes/dashboard.services.$id": typeof import("./app/routes/dashboard.services.$id.tsx");
  "routes/dashboard.audit-logs": typeof import("./app/routes/dashboard.audit-logs.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
  "routes/dashboard.settings.email-templates._index": typeof import("./app/routes/dashboard.settings.email-templates._index.tsx");
  "routes/dashboard.settings.email-templates.$type": typeof import("./app/routes/dashboard.settings.email-templates.$type.tsx");
  "routes/dashboard.settings.branding": typeof import("./app/routes/dashboard.settings.branding.tsx");
  "routes/dashboard.settings._index": typeof import("./app/routes/dashboard.settings._index.tsx");
  "routes/dashboard.settings.email": typeof import("./app/routes/dashboard.settings.email.tsx");
  "routes/dashboard.tenants": typeof import("./app/routes/dashboard.tenants.tsx");
  "routes/dashboard.tenants.$tenantId.invitations": typeof import("./app/routes/dashboard.tenants.$tenantId.invitations.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.roles": typeof import("./app/routes/dashboard.roles.tsx");
  "routes/dashboard.users": typeof import("./app/routes/dashboard.users.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
};