#!/usr/bin/env bash
# Generate a skeleton QA auto-test script from a QA document.
# Usage: ./gen-auto-script.sh docs/qa/integration/04-health-check.md
#
# Output: prints the target script path and creates the file if it does not exist.
# The generated script is a skeleton — scenario bodies contain TODO comments
# with the curl/SQL commands extracted from the QA doc.
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <qa-doc-path>" >&2
  exit 1
fi

DOC_PATH="$1"
if [[ ! -f "$DOC_PATH" ]]; then
  echo "File not found: $DOC_PATH" >&2
  exit 1
fi

# Derive script path: docs/qa/auth/07-public-endpoints.md -> scripts/qa/auto/auth-07-public-endpoints.sh
# For docs/qa/*: strip "docs/qa/" prefix
# For docs/security/*: strip "docs/" prefix (keeps security- prefix)
REL="${DOC_PATH#docs/qa/}"
if [[ "$REL" == "$DOC_PATH" ]]; then
  REL="${DOC_PATH#docs/}"
fi
REL="${REL%.md}"
SCRIPT_NAME="${REL//\//-}"
SCRIPT_PATH="scripts/qa/auto/${SCRIPT_NAME}.sh"

if [[ -f "$SCRIPT_PATH" ]]; then
  echo "Script already exists: $SCRIPT_PATH" >&2
  echo "$SCRIPT_PATH"
  exit 0
fi

# Extract doc id (for header comment)
DOC_ID="${DOC_PATH#docs/qa/}"
DOC_ID="${DOC_ID%.md}"

# Count scenarios
SCENARIO_COUNT=$(grep -c '^## 场景' "$DOC_PATH" 2>/dev/null || echo 0)

# Extract scenario titles
mapfile -t SCENARIO_TITLES < <(grep '^## 场景' "$DOC_PATH" | sed 's/^## 场景 [0-9]*[：:：]\s*//' | sed 's/^## 场景 [0-9]* //')

mkdir -p "$(dirname "$SCRIPT_PATH")"

{
  cat <<HEADER
#!/usr/bin/env bash
# QA Auto Test: ${DOC_ID}
# Doc: ${DOC_PATH}
# Scenarios: ${SCENARIO_COUNT}
# Generated by gen-auto-script.sh — fill in scenario bodies
set -euo pipefail
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
source "\$SCRIPT_DIR/../lib/runner.sh"

HEADER

  for ((i = 0; i < ${#SCENARIO_TITLES[@]}; i++)); do
    n=$((i + 1))
    title="${SCENARIO_TITLES[$i]}"
    cat <<SCENARIO
scenario $n "$title" '
  # TODO: implement test steps
  echo "SKIP: not yet implemented" >&2
'

SCENARIO
  done

  echo "run_all"
} > "$SCRIPT_PATH"

chmod +x "$SCRIPT_PATH"
echo "$SCRIPT_PATH"
